name: PR Validation

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Run linter
        run: cd frontend && npm run lint

      - name: Run tests
        run: cd frontend && npm run test

      - name: Build check
        run: cd frontend && npm run build
